#!/usr/bin/env python3
"""Draw the Melee-X dashboard icon: a bold bevelled X on a dark round badge
with a glowing rim (transparent background).

  tools/xbox/make_logo.py <out.png> [size]

Drawn from scratch with Pillow (no game or console art), so it can live in the
repo. xbox/assets/logo.png is generated by this; xbe_title_image.py turns it
into the XBE's $$XTIMAGE and default.tbn.
"""
import math
import sys

from PIL import Image, ImageChops, ImageDraw, ImageFilter

S = 1024  # work size; downscaled at the end for smooth edges
C = S / 2


def bar(angle, length, width, cut):
    """A bar through the centre at `angle`, its ends cut at 45 degrees the
    way the arms of an X meet the badge: a hexagon."""
    ux, uy = math.cos(angle), math.sin(angle)
    nx, ny = -uy, ux
    h, w = length / 2, width / 2
    pts = [(h, w - cut), (h - cut, w), (-h + cut, w), (-h, w - cut), (-h, -w + cut), (-h + cut, -w), (h - cut, -w),
           (h, -w + cut)]
    return [(C + x * ux + y * nx, C + x * uy + y * ny) for x, y in pts]


def x_mask(length, width, cut):
    m = Image.new("L", (S, S), 0)
    d = ImageDraw.Draw(m)
    d.polygon(bar(math.radians(45), length, width, cut), fill=255)
    d.polygon(bar(math.radians(-45), length, width, cut), fill=255)
    return m


def vgrad(top, bot, y0=0, y1=S):
    g = Image.new("RGBA", (S, S))
    d = ImageDraw.Draw(g)
    for y in range(S):
        t = min(1.0, max(0.0, (y - y0) / (y1 - y0)))
        d.line([(0, y), (S, y)], fill=tuple(int(a + (b - a) * t) for a, b in zip(top, bot)) + (255,))
    return g


def main():
    out = sys.argv[1]
    size = int(sys.argv[2]) if len(sys.argv) > 2 else 256
    img = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    r = 470

    # drop shadow under the badge
    sh = Image.new("L", (S, S), 0)
    ImageDraw.Draw(sh).ellipse((C - r, C - r + 18, C + r, C + r + 18), fill=150)
    img.paste(Image.new("RGBA", (S, S), (0, 0, 0, 255)), (0, 0), sh.filter(ImageFilter.GaussianBlur(16)))

    # badge: steel rim, then a deep blue-black face with a soft glow behind the X
    rim = Image.new("L", (S, S), 0)
    ImageDraw.Draw(rim).ellipse((C - r, C - r, C + r, C + r), fill=255)
    img.paste(vgrad((236, 240, 248), (96, 104, 122), C - r, C + r), (0, 0), rim)
    face_r = r - 34
    face = Image.new("L", (S, S), 0)
    ImageDraw.Draw(face).ellipse((C - face_r, C - face_r, C + face_r, C + face_r), fill=255)
    img.paste(vgrad((22, 30, 52), (6, 8, 16), C - face_r, C + face_r), (0, 0), face)
    glow = Image.new("L", (S, S), 0)
    ImageDraw.Draw(glow).ellipse((C - 300, C - 300, C + 300, C + 300), fill=150)
    glow = ImageChops.multiply(glow.filter(ImageFilter.GaussianBlur(90)), face)
    img.paste(Image.new("RGBA", (S, S), (255, 120, 20, 255)), (0, 0), glow)

    # the X: dark outline, a fiery gradient body, a bevel lit from the top left
    length, width, cut = 700, 170, 60
    outline = x_mask(length + 56, width + 56, cut + 23)
    body = x_mask(length, width, cut)
    img.paste(Image.new("RGBA", (S, S), (10, 10, 16, 255)), (0, 0), outline)
    img.paste(vgrad((255, 214, 64), (214, 24, 8), C - length / 2, C + length / 2), (0, 0), body)

    # bevel: the mask's edge, offset one way lit and the other way shaded
    edge = ImageChops.subtract(body, body.filter(ImageFilter.MinFilter(31)))
    lit = ImageChops.multiply(ImageChops.offset(edge, 6, 6), body)
    shade = ImageChops.multiply(ImageChops.offset(edge, -6, -6), body)
    img.paste(Image.new("RGBA", (S, S), (255, 255, 235, 255)), (0, 0), lit.point(lambda v: v * 130 // 255))
    img.paste(Image.new("RGBA", (S, S), (120, 10, 0, 255)), (0, 0), shade.point(lambda v: v * 150 // 255))

    # gloss: a soft white sheen on the upper half of the X
    gloss = Image.new("L", (S, S), 0)
    ImageDraw.Draw(gloss).ellipse((C - 420, C - 520, C + 420, C - 20), fill=60)
    gloss = ImageChops.multiply(gloss.filter(ImageFilter.GaussianBlur(30)), body.filter(ImageFilter.MinFilter(15)))
    img.paste(Image.new("RGBA", (S, S), (255, 255, 255, 255)), (0, 0), gloss)

    # sparkle where the arms cross
    sp = Image.new("L", (S, S), 0)
    d = ImageDraw.Draw(sp)
    d.polygon([(C, C - 150), (C + 22, C), (C, C + 150), (C - 22, C)], fill=255)
    d.polygon([(C - 150, C), (C, C - 22), (C + 150, C), (C, C + 22)], fill=255)
    sp = ImageChops.lighter(sp.filter(ImageFilter.GaussianBlur(3)), sp.filter(ImageFilter.GaussianBlur(24)))
    img.paste(Image.new("RGBA", (S, S), (255, 255, 255, 255)), (0, 0), sp.point(lambda v: v * 200 // 255))

    img.resize((size, size), Image.LANCZOS).save(out)
    print(f"wrote {out} ({size}x{size})")


if __name__ == "__main__":
    main()
